version: '3'
services:
#  app:
#    build: ./server
#    volumes:
#      - ./_data/:/_data
#    ports:
#      - 5011:5000


  db:
    image:  postgres:13
    ports:
      - 32700:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:  root
      POSTGRES_PASSWORD:  root
      POSTGRES_DB: s_posting